### ISSUE TITLE
Trajectory point transitions

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-consortium/descartes#10]
The `trajectory_pt` object contains a transition pointer.  To simplify things, I propose to remove the transition pointer and replace it with velocity and timing tolerances AT the trajectory point (acceleration could be added later).  These are somewhat redundant since all are dependent on the profile used between points.  To avoid this ambiguity/confusion, the profiles can be assumed to be well behaved and the density of the points ensures this.

A higher level path abstraction similar to gcode/robot code should be developed (in which case transition types are required), but for now we should assume dense trajectories.

**Comment by shaun-edwards** [comment]
These should probably be removed from the dense trajectory points.  Transitions will be handled in sparse trajectories.  See #51 for more details.

**Comment by Jmeyer1292** [comment]
Points no longer have transitions, but timing info instead.
