### ISSUE TITLE
Installing descartes

### ISSUE THREAD

**Issue by bluefish89** [ros-industrial-consortium/descartes#123]
Hi!
Just want to ask if its possible to add some information about how to install the descartes package either in the wiki or the readme.
I would like to use it, but don't know how to install it.
Best regards

**Comment by shaun-edwards** [comment]
@jrgnicho, looks like we forgot the most important part?  Can you add this info to the wiki....FYI, Descartes should be available in Hydro using `sudo apt-get install ros-hydro-descartes`.  Let me know if that doesn't work.

**Comment by bluefish89** [comment]
For indigo apt-get install is not yet available I think. In my despair I also asked in ros-answers. Here is [link](http://answers.ros.org/question/208963/installing-package-from-source-in-indigo/) with the great answer from gvdhoorn.
Thanks for the help and best regards!

**Comment by jrgnicho** [comment]
@shaun-edwards , I could not find ros-hydro-descartes as a debian package

**Comment by gavanderhoorn** [comment]
We're all still waiting for Tully to do a sync of Hydro.

It's installable if you use `ros-shadow-fixed`.

**Comment by 130s** [comment]
I added [install section](http://wiki.ros.org/action/info/descartes/Tutorials/Getting%20Started%20with%20Descartes?action=diff&rev2=34&rev1=33) on the ros wiki. Please feel free to edit it as it's wiki, but this ticket may be closed.
