### ISSUE TITLE
How to specify trajectory points with 6D pose?

### ISSUE THREAD

**Issue by Liangconghui** [ros-industrial-consortium/descartes#134]
Hi
I am a new user of the ROS-I Descartes package.
I want to specify several points with 6D pose (Position+Orientation).
In the tutorial1.cpp, I  just found out how to specify 3D position by using Eigen:Translation3d (x,y,z) function as shown below.
So my question is: are there any other function in Eigen to specify a 6D pose Cartesian space point?
Thanks!

Conghui 

// 1. Define sequence of points
  TrajectoryVec points;
  for (unsigned int i = 0; i < 10; ++i)
  {
    Eigen::Affine3d pose;
    pose = Eigen::Translation3d(0, 0, 0.1+0.05 \* i);
    //descartes_core::TrajectoryPtPtr pt = makeTolerancedCartesianPoint(pose);
    descartes_core::TrajectoryPtPtr pt = makeCartesianPoint(pose);
    points.push_back(pt);
  }

**Comment by Jmeyer1292** [comment]
Hey! Welcome to ROS-I. Thanks for giving Descartes a try.

An `Eigen::Affine3d` is a 4x4 homogeneous transformation matrix, so it can encode not just translation but your orientation as well. Please see http://eigen.tuxfamily.org/dox/group__TutorialGeometry.html for a good breakdown of Eigen's geometry capabilities.

There's lots of ways to specify rotations, but you can get at your transforms 3x3 rotation matrix with the `linear()` method of `Eigen::Affine3d`. So:

``` c++
Eigen::Affine3d pose;
pose = Eigen::Translation3d(0, 0, 1);

Eigen::Matrix3d m;
m = AngleAxisd(angle1, Vector3f::UnitZ())
    * AngleAxisd(angle2, Vector3f::UnitY())
    * AngleAxisd(angle3, Vector3f::UnitZ());

pose.linear() = m;
```

Again, there are lots of ways to specify rotation. So look at the tutorial.

If you have more questions or need more help, please feel free to ask.
