### ISSUE TITLE
Descartes Planning Spends a Lot of Time Calculating Edges

### ISSUE THREAD

**Issue by Jmeyer1292** [ros-industrial-consortium/descartes#151]
It appears that a large portion of the time spent building a planning graph is actually spent looking up joint positions from the joint solutions std::map. I believe we can refactor the `insertGraph` method to reduce this by passing the joint vectors generated during IK expansion directly to the edge builders.

**Comment by shaun-edwards** [comment]
@Jmeyer1292, can you provide the call graph and the details of your test case here.  It would be ideal if you could provide the test code/procedure as well.

**Comment by Jmeyer1292** [comment]
@shaun-edwards 

Here's a pretty typical example as produced by Valgrinds' callgrind tool. Note the right-most branch. Far more time is spent building edges than doing IK (at least when using some closed-form equivalent). The `linearWeight` function is doing the actual math but it is less than half of the cost of it's parent. Compiling under `RelWithDebInfo` indicates that this time is spent (mostly) searching the `std::map`.
![graph](https://cloud.githubusercontent.com/assets/4960180/13925770/a2d0c9e4-ef57-11e5-9249-9dfddea71d80.jpg)

**Comment by Jmeyer1292** [comment]
As far as test code/procedure, I've built a little package [here](https://github.com/Jmeyer1292/descartes/tree/benchmarks). It essentially uses the Roscon-2015 demo with some tweaks. It needs some work before it's ready to put into our main-line branch.

**Comment by Jmeyer1292** [comment]
#154 at least partially addresses this issue. I'm going to close this issue for the sake of clarity. Further performance questions will be continued in new threads.
