### ISSUE TITLE
Won't run on 32bit systems

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-consortium/descartes#16]
This library uses Eigen which has known issues on 32bit systems.  These issues can be addressed by compiler switches, but these are not present.

**Comment by shaun-edwards** [comment]
Not sure this will ever be addressed, but I wanted to capture this limitation in case anyone tries it.

**Comment by Jmeyer1292** [comment]
For the record, I believe defining the following should resolve the issue:

```
#define EIGEN_DONT_VECTORIZE 
#define EIGEN_DISABLE_UNALIGNED_ARRAY_ASSERT
```

You may be able to wrap those functions with a compiler test for your 32 bit architecture (such as **i386** for gcc and intel x86). 

More details: http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html
