### ISSUE TITLE
Auto format code?

### ISSUE THREAD

**Issue by davetcoleman** [ros-industrial-consortium/descartes#166]
Would you guys be opposed to me running my [ROS-customized clang-formatter](https://github.com/davetcoleman/roscpp_code_format) to this code base? It will enforce ROS standard styles within a second, recursively. I've been reading through the code and am a little frustrated by lines of code that are, for example, 137 characters long. I prefer to have two windows side by side when I code and this only works with the ROS standard of 120.

I'd create a PR that changes the whole code base in tiny ways.

**Comment by Jmeyer1292** [comment]
Go nuts. A lot of the "old code" is a mess in terms of style, convention, and readability. As long as a PR is just non-syntactic text changes, I don't care.
