### ISSUE TITLE
Install on Arch Linux

### ISSUE THREAD

**Issue by fred087** [ros-industrial-consortium/descartes#183]
when installing on Arch Linux, running ROS (indigo), I get that error :
/home/fred/system/ros/descartes/src/descartes/descartes_moveit/src/ikfast_moveit_state_adapter.cpp:83:3: erreur : ‘KinematicsResult’ is not a member of ‘kinematics’

**Comment by Jmeyer1292** [comment]
Hrm. I'll look into it. I may need your help to do some tests and reproduce the issue as I don't have an Arch install. Although, I could probably setup a VM.

**Comment by fred087** [comment]
I was on default branch indigo-devel when I had the error, I switched to indigo-training and it worked.
Certainly due to the fact the latest moveit-core package on arch is ros-indigo-moveit-core 0.6.15-2
