### ISSUE TITLE
How to change the speed from defined point to another point while using descartes?

### ISSUE THREAD

**Issue by jasonvank** [ros-industrial-consortium/descartes#189]
I am using UR10 and Linux 14.04 Indigo. I want to execute a cartesian motion planning. I used the two ways, one is using descartes package and another one is cartesian plan plugin.

I want to ask if it is possible to change the velocity of the robot moving from a defined point to another point, not the whole trajectory. I have already established the velocity limit and acceleration limits.

I have also tried the cartesian plan plugin. (https://github.com/ros-industrial-consortium/fermi.git) Does it have the way to change the velocity?

**Comment by shaun-edwards** [comment]
I believe "fermi" uses the standard MoveIt cartesian path planning service.  In which case, it tries to execute the cartesian path plan as fast as the joint velocity/acceleration limits will allow.  There may be a way to scale these limits with some of the new additions to MoveIt, but I'm not certain if these changes apply to cartesian path planning.  

Descartes allows you to specify the [time (or range of times)](https://github.com/ros-industrial-consortium/descartes/blob/indigo-devel/descartes_trajectory/include/descartes_trajectory/cart_trajectory_pt.h#L216) via the [timing constraint](https://github.com/ros-industrial-consortium/descartes/blob/indigo-devel/descartes_core/include/descartes_core/trajectory_timing_constraint.h).  This is probably the functionality you are looking for.  

FYI, specifying the trajectory timing could limit the ability to plan if the timing results in velocities or accelerations that exceed the robot capabilities (in other words, adding timing info could make a kinetically achievable plan, impossible).
