### ISSUE TITLE
Release into Indigo+ 

### ISSUE THREAD

**Issue by 130s** [ros-industrial-consortium/descartes#194]
Looks like we have one released into ROS Hydro, but not Indigo. 
Thank you.

**Comment by rivertam** [comment]
Kinetic would also be nice. =/

**Comment by BrettHemes-3M** [comment]
+1 to this.  Even a 0.0.4 release tag would be appreciated.

**Comment by 130s** [comment]
Closing myself as this is waay obsolete.
