### ISSUE TITLE
Consider removing process modifier from classes/filenames

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-consortium/descartes#2]
The current structures within Descartes are all prefixed with `process`.  However, the data types do not include any process data.

I'd like to propose that the `process` modifier be removed from the data types and file names and replaced with more generic types such as `waypoint` and `trajectory`.  Higher level classes will certainly contain process data, at which point, the prefix would seem more appropriate.

**Comment by shaun-edwards** [comment]
@dpsolomon, please weigh in.  I'd like to make this change soon.

**Comment by dpsolomon** [comment]
+1 I agree that process_\* is no longer appropriate
