### ISSUE TITLE
Trajectory point ID not implemented

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-consortium/descartes#20]
Trajectory point IDs are not currently populated on construction.  The IDs shall uniquely identify a point.  This means they can be used as keys to a map and to link other data/object to trajectory points.

**Comment by shaun-edwards** [comment]
The current plan is to utilized [boost::uuids](http://www.boost.org/doc/libs/1_48_0/libs/uuid/uuid.html#Nil).

**Comment by dpsolomon** [comment]
+2 If we can use unique ID's, then I think the samplers can hold a state for each TrajectoryPt they are associated with (#18)

**Comment by shaun-edwards** [comment]
Done...see PR #18
