### ISSUE TITLE
Any hope for using this with python?

### ISSUE THREAD

**Issue by jwhendy** [ros-industrial-consortium/descartes#201]
I'm going through the ROS-I tutorials, but translating to `python`. I got to this exercise and from my reading around, it's looking like this is currently `C++` only. Is that correct?

Any forecast/desire to port or make accessible via `python`? I'm also pretty new to ROS in general, so perhaps there's a known way to use any ROS library with `python`?

Thanks.

**Comment by Jmeyer1292** [comment]
If we wrote a ROS level interface, you could use Python. This would involve defining messages and services (or perhaps actions) that anyone could fill out and forward to a planning server node ala MoveIt.

I have trouble finding time and motivation to fix basic issues in C++, I have no desire to support more languages. I would not try to hold you back, however.
