### ISSUE TITLE
RePlanning

### ISSUE THREAD

**Issue by ghost** [ros-industrial-consortium/descartes#203]
Hey,

Is there a way to replan on real time or append new points and then re-calculate? 
Is there a way to plan a path with non-zero initial and ending conditions?

Thanks.

**Comment by Jmeyer1292** [comment]
To your first question:

1. I'm not sure about real-time, but you can append points through the PlannerBase interface. See [here](https://github.com/ros-industrial-consortium/descartes/blob/indigo-devel/descartes_core/include/descartes_core/path_planner_base.h#L86).

2. If by non zero you mean non-zero position, then yes: Any trajectory point, including an underconstrained one or a fully constrained joint position, can be the start or end of the path.
