### ISSUE TITLE
Trajectory point velocity/timing not implemented

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-consortium/descartes#21]
A key requirement of trajectory following is that the robot maintain a path velocity.  The path velocity and timing must be captured in the based data types.  In addition, when/where this data is populated still is TBD.  This data will also be used to determine if adjacent joint nodes in the planning graph are connected.  If the joint velocity required to move between joint points is too high, then the joint points are not connected.

**Comment by Jmeyer1292** [comment]
We now have some basic timing info in the base point type. If further refinements are necessary, we'll open new issues.
