### ISSUE TITLE
Moveit State Adapter requires tool/object frames

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-consortium/descartes#23]
The constructor for the `MoveitStateAdapter` requires the robot tool and object frames (i.e. strings) be identified.  See [here](https://github.com/ros-industrial-consortium/descartes/blob/hydro-devel/descartes_moveit/src/moveit_state_adapter.cpp#L31).

@dpsolomon commented the following:

> The design of the tool/wobj base was to allow planning with either a pure
> robot moveit package, or a custom one. In order to support that strategy, I
> think what was missing is a frame_id for each of the base frames.
> 
> I would rather see the frame id's added to the adaptor, and an identity
> frame used for the bases. That should help avoid future problems expanding
> the usage.
> 
> The calls to actually get ik should always solve between two known frames.
> Moveit::robotstate does some sort of automatic check and correction for
> difference between the planning frames and ik solver frames

The purpose of this issue is to continue the discussion.

**Comment by shaun-edwards** [comment]
@dpsolomon, can you elaborate on this?

> The design of the tool/wobj base was to allow planning with either a pure
> robot moveit package, or a custom one. In order to support that strategy, I
> think what was missing is a frame_id for each of the base frames.

I think you mean that the `trajectory_pt` already contains the base/tool offset frames.  However, the robot may also contain some additional offsets.  In particular (and if you can solve this problem, then it's a non-issue), we have a robot with a calibrated tool point.  The position of the calibrated frame is NOT stored in the URDF, rather it is published by the calibration code.  As a result, a planning group that contains the tool point cannot be defined.  To overcome this limitation, we pass the frame names to the `MoveitStateAdapter` and allow it to perform the necessary transform.  The transform may be done by MoveIt (if it is capable) or by an embedded tf (this is how we do it elsewhere).

**Comment by shaun-edwards** [comment]
This issue is a result of PR #14.

**Comment by dpsolomon** [comment]
> The position of the calibrated frame is NOT stored in the URDF, rather it is published by the calibration code. As a result, a planning group that contains the tool point cannot be defined.

This is a perfect example why the `TrajectoryPt` should hold its own transforms. If you know your tool transform externally relative to a known robot frame (ie wrist) then you can create all the `TrajectoryPts` using this tool transform as the `tool_base` frame. In this case I believe in this case the tool is static, so the `tool_pt` frame would be Identity with 0 tolerance.

Similarly, if you already have a set of `TrajectoryPts` before you calibrate the tool, simply update all the `TrajectoryPts` with this data before planning.

**Comment by shaun-edwards** [comment]
My thought is that trajectory points should be independent of the robot.  I should be able to share the same trajectory between two robots without changing them.  As it currently stands, both use cases are supported.  All I have to do is add a new constructor to `MoveitStateAdapter` that doesn't require the frame ids.

**Comment by jrgnicho** [comment]
Should this issue be closed?
