### ISSUE TITLE
console_bridge logging methods cause logging overhead

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-consortium/descartes#31]
The `console_bridge` methods like `logInform` and `logDebug` do not support streams.  As a result, some additional code is required when a stream is desired (mostly due to convenience and ease of use).

For example, the following [snippet](https://github.com/ros-industrial-consortium/descartes/blob/hydro-devel/descartes_moveit/src/moveit_state_adapter.cpp#L106-L108)

> std::stringstream msg;
> msg << "Found _first_ solution on " << sample_iter << " iteration, joint: " << joint_pose;
> logDebug(msg.str().c_str());

This code requires constructing a stream and converting several objects to strings, even in the case that DEBUG message are not enabled.

ROS Console and it's stream versions provide several advantages:
- Logging messages can be remove at run-time, see [here](http://wiki.ros.org/rosconsole#Compile-time_Logger_Removal).
- One line initialization of log messages.  This requires implementing the `<<` stream operator for most objects, but this is helpful in general (i.e. for testing).
- `ROS_*_STREAM` arguments (i.e. string conversion) are not evaluated (more than likely) according to [this](https://github.com/ros/ros_comm/blob/indigo-devel/tools/rosconsole/include/ros/console.h#L201).

**Comment by shaun-edwards** [comment]
@dpsolomon, what do you think?  If we choose not to link against ROS, a simple macro header could replace the ROS macros.

**Comment by dpsolomon** [comment]
- if you want to stay independent from ros for as long as possible, I think
  it is best to implement `class.toStr()` methods for new data types, and
  `toStr(class)` methods for existing types. This would allow you to keep the
  function as a log\* one liner, and will prevent most of the needless
  overhead.
- `ros_comm` is a pretty lightweight dependency to carry. Possibly even
  worthwhile using with our without ros.
- you could envision a template function that you pass an object, such as a
  method, and it uses the object's stream operator to create a string.
- `console_bridge` shows the function/ line number.
- `ros_comm` has pretty colors.

Sorry that this isn't a decision toward one or the other, but I figured I
could at least spell out some other comparisons. I'm pretty ambivalent,
I'll gladly use whichever one other people are comfortable with.

PS: `ros_comm` is far more mature, while `console_bridge` was more recently
done by ioan and someone else, and I am not sure which one is more actively
checked and fixed, but I do know that I've us far better documented.

**Comment by shaun-edwards** [comment]
OK, so the conclusion is to use ros console for logging.  The current calls to `console_bridge` can remain, but should be removed if someone touches that section of code.

**Comment by psturgeon** [comment]
I realize this is closed, but wanted to share an oddity I just ran across today (and as a result, a vote for ros console).

boost::uuids do not behave well as the first parameter in a log through console bridge (at times). Minimal example:
    TrajectoryPt::ID nilId = generate_nil();
    logInform("count %d CartID: %s:", 42, boost::uuids::to_string(nilId).c_str());
    logInform("CartID: %s: count:%d", boost::uuids::to_string(nilId).c_str(), 42);

Output:
[ INFO] [1416250614.658280257]: count 42 CartID: 00000000-0000-0000-0000-000000000000:
[ INFO] [1416250614.658443757]: 00000000-0000-0000-0000-000000000000: count:42

The string "CartID: " is dropped in the second log message. The behavior is the same if the log is directed to a stringstream first and then passed to logInform() and also if a non-nil uuid is used here.
The behavior seems very consistent here, but not in other places, ie the following log works fine:

```
logInform("PreviousID[%s].links_.id_next = %s", boost::uuids::to_string(previous_id).c_str(), boost::uuids::to_string(point_link->id).c_str());
```

I haven't looked too deep into what may be causing this behavior, but it's something to keep in mind in case logging isn't behaving correctly in places. It should be a moot issue though if logs are converted over to ros console.
