### ISSUE TITLE
Equality comparison operators missing for TrajectoryPt types

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-consortium/descartes#32]
Cartesian and Joint trajectory point types do not define equality.  This makes testing difficult.  Testing equality of these types is non-trivial given their complexity and class hieararchy.  See [here](http://stackoverflow.com/questions/1691007/whats-the-right-way-to-overload-operator-for-a-class-hierarchy) for an example implementation.  Note, it does appear that most approaches for implementing the `==` operator are meant to protect from bugs in development, not necessarily functional issues.

**Comment by jrgnicho** [comment]
@shaun-edwards has this been addressed.  If not, is it still needed?

**Comment by shaun-edwards** [comment]
It is still needed for testing purposes.

**Comment by Jmeyer1292** [comment]
I feel like this is low value and potentially brittle. We have `copy` and `clone` functions which might fulfill many of the potential use cases of this code. This issue can be reopened if required.
