### ISSUE TITLE
Graph planning algorithm is slow when solving for large number (1000's) of points

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-consortium/descartes#37]
The current (working) graph search algorithm is slow when a trajectory with 1000's of points is desired.  Such trajectories could be common, especially when trying to control positions with high accuracy or when performing linear motion with a manipulator.  Preliminary tests indicate that graph construction is the expensive(time) operation.

For example, assume the following: 1000 Cartesian trajectory points specified, with a free yaw rotation (at 1 degree resolution - required for smooth motion), on a standard 6 DOF industrial robot, w/o collision checking.  The number of IK calls (approximately the same as number of nodes) in the graph (i.e. that must be constructed) is:

1000 Cart pts \* 360 yaw samples/Cart pt \* 10 IK solutions (assuming KDL) = 3.6M (IK solver calls)

Current tests have been executed without yaw sampling and take several seconds to load.  Even a sparse yaw sampling (which isn't good for motion smoothness) will result in very long graph construction times.

An obvious improvement to the existing algorithm is to use IKFast instead of KDL.  In the past we have seen a 10x faster solve time with IKFast.  Our results may be better given IKFast doesn't need to "search" for multiple IK solutions.  It can calculated them all directly.  

While this is an obvious change, it will not solve the main problem: The current planning algorithm does not scale with time.  Furthermore, simple planning problems take as long as to solve as more complex ones.

**Comment by shaun-edwards** [comment]
I propose an adaptive trajectory sampling that starts with a sparse set of trajectory points and interpolates between sparse points, while still maintaining the dense trajectory constraints.  If any dense trajectory constraint is not achievable given the sparse plan, the unachievable point is added to the trajectory and resolved.

Here is the algorithm in pseudo-code

```
For each N sub-samples in trajectory:
  Add sub-sample to graph //uses existing graph planner API
  Solve graph
For each P trajectory-pt in trajectory
  If ( trajectory-pt.getClosestJointPose(interpolated joint pose, model) ) //must be implemented in trajectory pt
     Add joint pose to solution
  Else
     Add point to graph //lightweight operation in current solver
     (Re) Solve graph
     Reset loop

```

Under a best case scenario (i.e. the sparse trajectory results in a solution for the dense trajectory), the number of IK solutions can be calculated as follows, with the following assumptions:
- the required yaw sampling is also less dense (every 10 degrees or further) since trajectory points will be interpolated between sparse points
- the number of `N` sub-samples is extremely low for well behaved problems (as low as 2 points, but we will assume 1%)

`10 Cart pts * 36 yaw samples/Cart pt * 10 IK solutions (assuming KDL) = 3.6K (IK solver calls)`

In addition, IK solver calls are required in order to interpolate between points (1 per point)

`990 Cart pts * 1 IK solution/pt = 990 additional solver calls.`

Each time a pt is added to the graph, the dense trajectory IK solutions are recalculated, so if `M` additional points are added, then the total IK solver calls is:

`3.6K (original sparse graph) + M * 990` (actually the math is more complex, but this bounds it).

Given the simplistic math, the adaptive trajectory sampling would become worse than the brute force solution at approximately `M~3600` iterations.  Note, this means the adaptive method will never be slower than the brute force method (this is because the yaw is sampled at a sparser interval).  If the original sampling is used, then `M~360` iterations is when the adaptive method become worse.

The main benefit of this approach is that if a simple answer exists, the adaptive solver will find it very quickly.  However, if the problem is very complex (assumed to be a rare condition), the adaptive method will still find it (although taking a longer time than the brute force solution).

**Comment by shaun-edwards** [comment]
@psturgeon, @dpsolomon - Please feel free to comment on my proposed solution or add your own.

**Comment by ClayFlannigan** [comment]
I worry about the idea of creating a complete graph when, intuitively, most common problems we see have direct solutions; it feels very wasteful to fully populate all those states when the solution could be guided by a simple sampling or heuristic on the state space.  Thus, I like your idea of being "adaptive" and refining the solution iteratively.  Because our problems are mostly convex, I think this should work fine.

It did make me think about an A\* search, however.  [Boost's implementation](http://www.boost.org/doc/libs/1_38_0/libs/graph/doc/astar_search.html) permits graph population on the fly.  See discussion about implicit graphs.  Could this not similarly reduce the number of states that need to be generated?

**Comment by shaun-edwards** [comment]
@ClayFlannigan, thanks for the discussion.  @dpsolomon  and I took a look at A\* a while back.  At that time, we only considered fully constrained Cartesian paths (i.e. full 6DOF).  It's not exactly what we are discussing here, but it may help to illustrate a few points.

A brute force approach (i.e. populating the whole graph results in the following number of IK calls):

`1000 Cart pts * 10 IK solutions (assuming KDL) = 10K (IK solver/collision calls)`

An A\* start approach requires the same number of calls because at each _level_ in the graph, the nodes can be fully connected (I'm sure there is a better "graph" vernacular for this).  In other words, for each Cartesian point, there exists a number of joint solutions.  Even if we are _at_ a particular joint solution in our A\* search, the joint solutions for the next Cartesian point must all be calculated.  Only at the joint level can we determine if two nodes in the graph are connected (i.e. if a transition is physically/dyamically possible).  If we had a method that could calculate only the subset of nodes that are reachable, then there would be a benefit to A\* (if anybody knows of such a method, please let me know).  In this case, A\* does not search faster, nor does it have a smaller footprint.

With semi-constrained Cartesian points, the discussion becomes more complicated.  In this case, there are really two graphs, one through Cartesian space, and then a larger graph through joint space.  However, because we can only determined connected-ness of adjacent points in joint space, using A\* again does not result in fewer IK calls.  

One thing we hadn't considered before is that we may be able to determine connected-ness of adjacent Cartesian points.  For example, the Jacobian at a joint solution could be used to estimate whether an adjacent Cartesian point would be reachable within joint dynamic constraints, _without_ calculating IK.

Some additional notes on A*
- The sampling within Cartesian space would have to be done at a dense level to ensure smooth motion, so any improvement in search efficiency may not be better than the proposed adaptive strategy.  The same would go for the memory footprint.
-  The current approach of modifying the graph in memory and resolving whenever a point is changed/added/deleted is not so straightforward.  It's this capability that makes the GUI appear responsive.  It's also this same ability that makes the adaptive approach possible (although this would be a circular argument for an adaptive/brute force approach ).

There could be an opportunity for performance improvement using A*, but  regardless of the search method, any improvement would be small compared to the adaptive method (assuming the adaptive method achieves a viable plan at the sparsest level).

**Comment by isucan** [comment]
I think multiple levels of resolution as @shaun-edwards suggests is a good idea and definitely more efficient. However, this may preclude finding some solutions: If a solution is not available at the coarser level, it may still be the case the solution is available at the finer grained level.

About @ClayFlannigan 's suggestion: I was going to suggest the same. A\* in boost can work on implicit graphs. So you can think of the graph as being full, but no IK states would be populated. Only when a node is visited and checked for collision / validated in some way, do we need to call IK. For simple environments this will expand very few nodes and thus perform very few IK calls. Of course, in the worst case the full graph would be expanded.

Personally, I would implement both ideas. Do a two-level search as @shaun-edwards suggests, but then represent the graphs implicitly and lazily populate the IK states, as A\* visits them.

**Comment by dpsolomon** [comment]
+1. I have always been a fan of an adaptive sampling technique, even when we didn't know if we would need it.

Remember that this all depends on what you are trying to solve. If you are looking for the first acceptable path, then you can save a lot of time by only sampling until you satisfy the path constraints.
If you want the optimal solution, full graph expansion seems like a valid approach, with the obvious sacrifice of time.

@shaun-edwards  I like that the strategy you have laid out will give fairly smooth solutions because you are interpolating between points. What I am not sure about is if finding the "best path" through those 10 key points is any better than picking a random configuration at each of the key points and trying to interpolate through those. What I mean is that if the key points are far enough apart, the best graph solution probably has little correspondence to a good trajectory. Unfortunately, I don't have a good metric to know how densely to space those initial key points to promote higher confidence in generating a good trajectory.

An alternative strategy that sort of follows the spirit of a \* search could be implemented as follows:

```
Populate the graph with the default yaw value (all 1000 points)
Loop
  Solve the graph
  Crawl the solution until a segment is found that violates some path constraint (e.g. large joint motion)
    If (no violating segments are found):
      break
    else:
    Add yaw samples to the endpoints of that segment
    (optional) Also add yaw samples to the points adjacent to the segment endpoints
```

Another riff on this could be:

```
Populate the graph with the default yaw value (all 1000 points)
Loop:
  Solve the graph
  Find all segments in the solution that violate some path constraint (e.g. large joint motion)
    If (no violating segments are found):
      break
    else:
      For each segment in violation:
        Add yaw samples to the endpoints of that segment
        (optional) Also add yaw samples to the points adjacent to the segment endpoints
```

_Note: Each subsequent yaw sample should be taken farther and farther away from the default pose._
The downside to these strategies is that if a good solution does not lie near the default pose, it could take a long time to find it. Could there be some way of merging these two strategies?

**Comment by shaun-edwards** [comment]
Closing this out.  The `SparseTrajectoryPlanner` implements the ideas discussed here.  There are still some improvements to be made to plan under all types of constraints, but in general the planner works.
