### ISSUE TITLE
Position/orientation nominal values

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-consortium/descartes#4]
The  process point/waypoint structure doesn't capture nominal values.  A waypoint will likely have a desired value, with some error bound or tolerance.  When at all possible, the nominal value should be held.  The tolerance zone should only be used when the process requires/allows for it.

**Comment by shaun-edwards** [comment]
@dpsolomon, please comment.

**Comment by dpsolomon** [comment]
-1 each waypoint contains a set of frames and toleranced frames (inherits from frames). A frame is mostly just an affine - that is the default pose if the point.

I will write up the thought I had behind this layout in the readme, I think it will be clearer how it might work then.
