### ISSUE TITLE
Interpolator Class

### ISSUE THREAD

**Issue by jrgnicho** [ros-industrial-consortium/descartes#51]
The current descartes planner (PlanningGraph, SparsePlanner) only operate on dense trajectories.  Thus an Interpolator would produce intermediate points between the sparse waypoints and then pass the interpolated dense trajectory to a planner.  In addition, it should allow for several interpolation strategies (cartesian, joint, etc) and tolerances (waypoint zone) for each waypoint.

**Comment by shaun-edwards** [comment]
@jrgnicho, we need more detail on this one.  I'd like to point a few people to this bug, but there needs to be more details.  What's the input?  What's the output?  What data structures are envisioned?  Can we point to existing robot languages as an example?

**Comment by Jmeyer1292** [comment]
While useful, I feel that this sort of functionality belongs to a higher level package that wraps descartes as it is now.
