### ISSUE TITLE
Update MoveIt KinematicsBase plugin to include an "getAllIK" method

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-consortium/descartes#53]
The current MoveIt [KinematicsBase](http://docs.ros.org/indigo/api/moveit_core/html/classkinematics_1_1KinematicsBase.html) class does not have a method to return multiple joint solutions for a single Cartesian point.  The Descartes graph style path planners require such a method.  To make use of MoveIt IK solutions in Descartes, we will need to add such a method.

There was some previous [discussion](https://groups.google.com/forum/#!msg/moveit-users/IGkUhU2CGu0/WADuA85GSmgJ) on this.  

Please coordinate with the @ros-planning/moveit_core team  to ensure this addition is accepted.

**Comment by davetcoleman** [comment]
i believe this issue can now be closed: https://github.com/ros-planning/moveit_core/pull/231/files#diff-a5fd2a2878fc18dd4784fc964898027cR179
