### ISSUE TITLE
core: build script hardcodes cmake build type (set to debug)

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial-consortium/descartes#67]
As per title. See [descartes_core/CMakeLists.txt](https://github.com/ros-industrial-consortium/descartes/blob/672b9c0907755ef23bfc92905942425cc31e19e0/descartes_core/CMakeLists.txt#L4).

Not sure if this is _by design_, but it is considered bad practice to set the CMake build type from within a `CMakeLists.txt` file. Recommended is to do it at configuration time (ie: `catkin_make -DCMAKE_BUILD_TYPE=...`).

**Comment by shaun-edwards** [comment]
@jrgnicho, this is a high priority fix.  We should also see if this affects `amos`.  @Jmeyer1292, this might have an affect on `godel`.

**Comment by gavanderhoorn** [comment]
Fixed in #68.
