### ISSUE TITLE
Inconsistent Arguments to RobotModel initialize method

### ISSUE THREAD

**Issue by Jmeyer1292** [ros-industrial-consortium/descartes#70]
This is a minor quibble, but the current RobotModel initialize method takes the robot description string by value instead of by reference. This appears to be a simple typo, but I wanted to check.

https://github.com/ros-industrial-consortium/descartes/blob/hydro-devel/descartes_core/include/descartes_core/robot_model.h#L102

**Comment by jrgnicho** [comment]
@Jmeyer1292  can this be closed?
