### ISSUE TITLE
Incorrect discretization in the CartesianPt getCartesianPoses method

### ISSUE THREAD

**Issue by jrgnicho** [ros-industrial-consortium/descartes#84]
The discretization of the cartesian poses in the [getCartesianPoses()](https://github.com/ros-industrial-consortium/descartes/blob/hydro-devel/descartes_trajectory/src/cart_trajectory_pt.cpp#L187) method does not take into account the **tool_pt_** and **tool_base_** members when performing this computation.  The correct way is already implemented in the [getJointPoses()](https://github.com/ros-industrial-consortium/descartes/blob/hydro-devel/descartes_trajectory/src/cart_trajectory_pt.cpp#L300) method.

**Comment by Jmeyer1292** [comment]
Addresed by #85
