### ISSUE TITLE
Update Descartes maintainers

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-consortium/descartes#90]
The Descartes maintainers should be updated in each package.xml.

Dan Solomon should be removed (but kept as an author).  Please add @jrgnicho, @shaun-edwards, and @Jmeyer1292.

Maintainers get an email when the build system detects a failure.

**Comment by shaun-edwards** [comment]
@Jmeyer1292, can you please address as soon as possible.

**Comment by shaun-edwards** [comment]
@madratman, @Jmeyer1292 knows the right emails to add (they aren't necessarily github emails).  Thanks for offering though.

**Comment by madratman** [comment]
Yes, I realized just now it should be jnicho instead of jorge.nicho as I have done in PR#92

**Comment by Jmeyer1292** [comment]
Addressed in #93. Closing.
