### ISSUE TITLE
Create Descartes meta-package

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-consortium/descartes#91]
The Descartes [wiki page](http://wiki.ros.org/descartes) does not include auto-generated content because a meta-package does not exist.  An example meta-package can be found in [industrial_core](https://github.com/ros-industrial/industrial_core/tree/indigo-devel/industrial_core).

**Comment by madratman** [comment]
I'll get this done.

**Comment by shaun-edwards** [comment]
@madratman, thanks for helping out.

**Comment by madratman** [comment]
Shall I do #90 as well?

**Comment by Jmeyer1292** [comment]
Should this be closed?

**Comment by shaun-edwards** [comment]
Fixed in #92
